name: covid19
channels:
  - defaults
dependencies:
  - python>3.7.0
  - pip
  - numpy
  - pandas>1.0.0
  - shapely
  - gdal
  - fiona
  - pyproj
  - six
  - rtree
  - geopandas
  - rasterio
  - html5lib
  - ipython
  - ipykernel
  - jupyter
  - matplotlib
  - pymc3
  - pyqtgraph
  - seaborn
  - selenium
  - statsmodels
  - svgutils
  - tqdm
  - wikipedia
  - xlrd
  - pip:
      - pipwin
      - countryinfo
      - qwikidata
      - svgpathtools
      - wikidata
      - wptools