name: covid19
channels:
  - defaults
  - conda-forge
dependencies:
  - html5lib
  - ipython
  - jupyter
  - matplotlib
  - pandas>1.0.0
  - pip
  - pymc3
  - pyqtgraph
  - python>3.7.0
  - seaborn
  - selenium
  - statsmodels
  - svgutils
  - tqdm
  - wikipedia
  - xlrd
  - pip:
      - countryinfo
      - qwikidata
      - svgpathtools
      - wikidata
      - wptools