name: covid19
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.7.0
  - pandas>1.0.0
  - conda
  - conda-build
  - fiona
  - gdal
  - geopandas
  - html5lib
  - ipython
  - jupyter
  - ipykernel
  - lxml
  - matplotlib
  - numpy
  - openpyxl
  - pip
  - pydub
  - pymc3
  - pyproj
  - pyqtgraph
  - rasterio
  - rtree
  - seaborn
  - selenium
  - shapely
  - six
  - statsmodels
  - svgutils
  - tqdm
  - wikipedia
  - xlrd
  - pip:
      - countryinfo
      - pipwin
      - qwikidata
      - svgpathtools
      - wikidata
      - wptools