name: covid19
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.7.0
  - pandas>1.0.0
  - conda
  - conda-build
  - geopandas
  - html5lib
  - ipykernel
  - ipython
  - jupyter
  - lxml
  - matplotlib
  - numpy
  - pip
  - scipy
  - seaborn
  - selenium
  - shapely
  - statsmodels
  - svgutils
  - tqdm
  - wikipedia
  - xlrd